const BookingEvents = {
    ACCEPTED: 'BOOKING_ACCEPTED',
    MAX_BOOKING: 'MAX_BOOKING_REACHED',
    NOT_ACCEPTED: 'BOOKINGS_NOT_ACCEPTED',
    RESERVATION_COMPLETED: 'RESERVATION_COMPLETED'
}

module.exports = BookingEvents;